=== lunarnet76/CRUDsader/Art/Adapter/Map/Loader/Xml.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT art (attributeTypes,classes)>
    
    <!ELEMENT attributeTypes (attributeType+)>
         <!ELEMENT attributeType EMPTY>
            <!ATTLIST attributeType alias CDATA #REQUIRED>
            <!ATTLIST attributeType length CDATA #REQUIRED>
            <!ATTLIST attributeType databaseType CDATA #IMPLIED>
            <!ATTLIST attributeType class CDATA #IMPLIED>
            <!ATTLIST attributeType options CDATA #IMPLIED>

    <!ELEMENT classes (class+)>
        <!ELEMENT class (inherit?,attribute*,associated*)>
            <!ATTLIST class name CDATA #REQUIRED>
            <!ATTLIST class databaseTable CDATA #IMPLIED>
            <!ATTLIST class identity CDATA #IMPLIED><!-- col1,col2 -->
            <!ATTLIST class databaseIdField CDATA #IMPLIED><!-- col1,col2 -->
            <!ATTLIST class association (true|false) #IMPLIED><!-- association class are UNIQUE to an association, and named with the association table name-->

            <!ELEMENT inherit EMPTY>
                <!ATTLIST inherit from CDATA #REQUIRED>
                <!ATTLIST inherit implementation (table|concrete|hierarchy) #IMPLIED>

            <!ELEMENT attribute EMPTY>
                <!ATTLIST attribute name                CDATA               #REQUIRED>
                <!ATTLIST attribute mandatory           (true|false)        #IMPLIED>
                <!ATTLIST attribute default             CDATA               #IMPLIED>
                <!ATTLIST attribute databaseField       CDATA               #IMPLIED>
                <!ATTLIST attribute type                CDATA               #IMPLIED>
                <!ATTLIST attribute searchable          (true|false)        #IMPLIED>
                <!ATTLIST attribute calculated          (true|false)        #IMPLIED>

           <!ELEMENT associated EMPTY>
                <!ATTLIST associated to             CDATA                                   #REQUIRED>
                <!ATTLIST associated reference (external|internal|class)                    #IMPLIED>
                <!ATTLIST associated name           CDATA                                   #IMPLIED>
                <!ATTLIST associated min            CDATA                                   #IMPLIED>
                <!ATTLIST associated max            CDATA                                   #IMPLIED>
                <!ATTLIST associated composition (true|false)                    #IMPLIED>
                <!ATTLIST associated databaseTable CDATA                          #IMPLIED>

=== lunarnet76/CRUDsader/Test/Parts/orm.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE art SYSTEM "../../Art/Adapter/Map/Loader/Xml.dtd" >
<art>
    <attributeTypes>
        <attributeType alias="default" databaseType="VARCHAR" length="32" />
        <attributeType alias="email" class="email" options="'lookup':false" databaseType="VARCHAR" length="255"/>
        <attributeType alias="date"  class="date"  options="'today':true" databaseType="DATE" length="false"/>
    </attributeTypes>
    
    <classes>
        <class name="contact" identity="name" databaseTable="Tcontact" databaseIdField="PKcontactid">
            <attribute name="name" databaseField="Fname" required="true" />
            <associated to="group" name="hasGroup"  min="0"     max="1"     reference="internal"   internalField="FKgroup" composition="true"  />
            <associated to="email" name="hasEmail"  min="0"     max="*"     reference="external"   externalField="FKcontact" composition="true"  />
            <associated to="address" name="hasAddress"  min="0"     max="1"     reference="external"   externalField="FKcontact" composition="true"  />
            <associated to="webSite" name="hasWebSite"  min="0"     max="*"     reference="table"  databaseTable="C2Wb" internalField="FK2contact" externalField="FK2website" databaseIdField="id" composition="false"  />
        </class>
        <class name="person" inherit="contact" databaseTable="Tperson" databaseIdField="PKpersonid">
            <attribute name="title" databaseField="Ftitle" required="true" />
        </class>
        
        <class name="group">
            <attribute name="name" databaseField="Fname"/>
        </class>
        <class name="email">
            <attribute name="address" databaseField="Faddress"/>
            <attribute name="created" databaseField="Fwhen" type="date"/>
            <associated to="webSite" reference="internal" internalField="FKwebSite" min="0" max="1"/>
        </class>
        <class name="address">
            <attribute name="street" databaseField="Fstreet"/>
            <attribute name="streetNumber" databaseField="FstreetNumber"/>
            <attribute name="city" databaseField="Fcity"/>
            <attribute name="country" databaseField="Fcountry"/>
        </class>
        <class name="webSite" inherit="contact">
            <attribute name="url" databaseField="Furl"/>
        </class>
    </classes>
</art>

=== lunarnet76/CRUDsader/Art/Test/parts/map.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE art SYSTEM "../../Adapter/Map/Loader/Xml.dtd" >
<art>
    <attributeTypes>
        <attributeType alias="default" databaseType="VARCHAR" length="32"/>
        <attributeType alias="email" class="email" options="'lookup':false" databaseType="VARCHAR" length="255"/>
        <attributeType alias="date"  class="date"  options="'today':true" databaseType="DATE" length="false"/>
    </attributeTypes>
    
    <classes>
        <class name="contact" databaseTable="Tcontact" identity="designation" databaseIdField="contact_id">
            <attribute name="designation" calculated="false" searchable="true" databaseField="designation" />
            
            <associated to="login"    min="0" max="1" reference="external" composition="true" name="hasLogin" />
            <associated to="photo"    min="0" max="*" reference="external" composition="true" />
            <associated to="company"    min="0" max="1" reference="internal"  />
            <associated to="address"    min="0" max="1" reference="class" name="hasAddress"  />
            
        </class>
        
        <class name="hasAddress" association="true">
            <associated to="company" reference="internal"/>
        </class>
        
        <class name="login">
            <attribute name="name"/>
        </class>
         <class name="photo" >
            <attribute name="name"/>
            <associated to="contact" min="1" reference="internal"/>
        </class>
        <class name="company" >
            <attribute name="name"/>
            <associated to="address" min="0" max="1" reference="external" />
        </class>
        <class name="address">
            <attribute name="name"/>
            <associated to="contact"    min="0" max="*" reference="class"  name="hasAddress" />
        </class>
        
      
       
    </classes>
</art>

=== lunarnet76/CRUDsader/Test/parts/map.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE art SYSTEM "../../Art/Adapter/Map/Loader/Xml.dtd" >
<art>
    <attributeTypes>
        <attributeType alias="default" databaseType="VARCHAR" length="32"/>
        <attributeType alias="email" class="email" options="'lookup':false" databaseType="VARCHAR" length="255"/>
        <attributeType alias="date"  class="date"  options="'today':true" databaseType="DATE" length="false"/>
    </attributeTypes>
    
    <classes>
        <class name="contact" identity="name" databaseTable="Tcontact" databaseIdField="PKid">
            <attribute name="name" databaseField="Fname" />
            <associated to="group" name="hasGroup"  min="0"     max="1"     reference="internal"   internalField="FKgroup" composition="true"  />
            <associated to="email" name="hasEmail"  min="0"     max="*"     reference="external"   externalField="FKcontact" composition="true"  />
            <associated to="address" name="hasAddress"  min="0"     max="1"     reference="external"   externalField="FKcontact" composition="true"  />
            <associated to="webSite" name="hasWebSite"  min="0"     max="*"     reference="table"  databaseTable="C2Wb" internalField="FK2contact" externalField="FK2website" composition="true"  />
        </class>
        <class name="person" inherit="contact" databaseTable="Tperson" databaseIdField="PKid"/>
        
        
        <class name="group">
            <attribute name="name" databaseField="Fname"/>
        </class>
        <class name="email">
            <attribute name="address" databaseField="Faddress"/>
        </class>
        <class name="address">
            <attribute name="street" databaseField="Fstreet"/>
            <attribute name="streetNumber" databaseField="FstreetNumber"/>
            <attribute name="city" databaseField="Fcity"/>
            <attribute name="country" databaseField="Fcountry"/>
        </class>
        <class name="webSite">
            <attribute name="url" databaseField="Furl"/>
        </class>
    </classes>
</art>
